# Ensure lint metadata is tested
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: ensure-metadata-tests

jobs:
  ensure-metadata-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Ensure lint metadata is tested
        run: |
          options(crayon.enabled = TRUE)
          callr::rscript(".dev/lint_metadata_test.R")
        shell: Rscript {0}
